spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/hotdogtaz
  datasource:
    url: jdbc:postgresql://localhost:5432/hotdogtaz
    username: hotdogtaz
    password: hotdogtaz123

keycloak:
  admin:
    server-url: http://localhost:8180
    username: admin
    password: admin123
  app:
    realm: hotdogtaz