spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/hotdogtaz
  datasource:
    url: jdbc:postgresql://localhost:5432/hotdogtaz
    username: hotdogtaz
    password: hotdogtaz123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true